### ISSUE TITLE
fct overflow when a flow is ultra long and slow

### ISSUE THREAD

**Issue by zylan29** [HKUST-SING/TrafficGenerator#11]

**Comment by baiwei0427** [comment]
I will fix this as soon as possible.

**Comment by baiwei0427** [comment]
This issue is not due to the data type. The reason is that we terminate all connections so quickly (just wait for 5 seconds by default) that some flows cannot be finished. Consequently, we can extremely large FCT results for unfinished flows since their completion times are zero.
