### ISSUE TITLE
请教network load是如何实现的

### ISSUE THREAD

**Issue by NICOlikeRest** [HKUST-SING/TrafficGenerator#30]
老师您好，我想问一下Enabling ECN in Multi-Service  Multi-Queue Data Centers文章中的network load是如何实现的。比如说链路带宽为1000Mbps，那么TrafficGenerator中-b 200是否代表network load为20% ， -b 400是否代表着40%的network load， -b 600代表着60%的network load
非常感谢！

**Comment by baiwei0427** [comment]
@NICOlikeRest  network load本质就是目标链路利用率 x 链路带宽，你的理解是对的

**Comment by NICOlikeRest** [comment]
非常感谢！
